name: noheva_visitor_ui
description: Noheva visitor UI project

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.12

environment:
  sdk: ">=3.0.6 <4.0.0"

scripts:
  gen: dart run build_runner build --delete-conflicting-outputs

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  openapi_generator_annotations: ^4.0.0
  flutter_dotenv: ^5.1.0
  simple_logger: ^1.9.0+2
  noheva_api:
    path: noheva-api
  device_info_plus: ^9.1.1
  mqtt_client: ^10.0.0
  typed_data: ^1.3.1
  json_annotation: ^4.8.1
  android_id: ^0.3.3
  drift: ^2.10.0
  path_provider: ^2.0.15
  path: ^1.8.3
  sqlite3_flutter_libs: ^0.5.15
  package_info_plus: ^4.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_widget_from_html_core:
    git:
      url: https://github.com/Metatavu/flutter_widget_from_html.git
      ref: 7d88c2dc35981438ed4fa494b3513d8bc5404542
      path: packages/core
  video_player: ^2.6.1
  video_player_macos: ^2.0.1
  collection: ^1.17.2
  html: ^0.15.4
  built_value: ^8.6.2
  crypto: ^3.0.3
  csslib: ^1.0.0
  window_manager: ^0.3.6
  flutter_app_installer: ^1.0.0
  flutter_sparkle: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  openapi_generator: ^4.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  drift_dev: ^2.10.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
